info:
  namespace: smp2items
items:
  hearthstone:
    display_name: '%#0086D1%源初的回响'
    lore:
    - '&f右键使用传送到主城'
    - '&f一旦启用即消耗耐久'
    - '%#0086D1%&l稀有级'
    permission: hearthstone
    durability:
      max_custom_durability: 30
    resource:
      material: SHEARS
      generate: true
      textures:
      - items/hearth_stone.png
    item_flags:
    - HIDE_ATTRIBUTES
    - HIDE_DESTROYS
    - HIDE_ENCHANTS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_UNBREAKABLE
    blocked_enchants:
    - ALL
    events_cooldown: 1200
    events:
      interact:
        right:
          decrement_durability:
            amount: 1
          execute_commands:
            cmd:
              command: 'Hearthstone {player}'
              as_console: true
            