info:
  namespace: smp2items
items:
  hearthstone:
    display_name: '%#0086D1%源初的回响'
    lore:
    - '&f右键使用传送到主城'
    - '%#0086D1%&l稀有级'
    permission: hearthstone
    durability:
      max_custom_durability: 30
    resource:
      material: SHEARS
      generate: true
      textures:
      - items/hearth_stone.png
    item_flags:
    - HIDE_ATTRIBUTES
    - HIDE_DESTROYS
    - HIDE_ENCHANTS
    - HIDE_PLACED_ON
    - HIDE_POTION_EFFECTS
    - HIDE_UNBREAKABLE
    blocked_enchants:
    - ALL
    all_actions_permission: 'smp2items.usage.hearthstone'
    events_cooldown: 1200
    events:
      interact:
        right:
          decrement_durability:
            amount: 1
          play_sound:
            name: smp2items:effects.castmagic
            volume: 1
            pitch: 1 
          execute_commands:
            cmd1:
              command: 'tellraw {player} {"text":"正在传送到主城","color":"gold"}'
            cmd2:
              command: '/mv spawn {player}'
              delay: 5